spring:
  application:
    name: org-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /api/v1/org/api-docs
  swagger-ui:
    path: /api/v1/org/swagger-ui.html

app:
  gateway-url: ${GATEWAY_URL}

gateway:
  internal:
    secret: ${GATEWAY_INTERNAL_SECRET}
