CREATE DATABASE IF NOT EXISTS nexaris_authservice;
USE nexaris_authservice;

CREATE TABLE roles (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(50) NOT NULL UNIQUE,
   description VARCHAR(255)
);


CREATE TABLE countries (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    code VARCHAR(2) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    phone_code VARCHAR(10)
);

CREATE TABLE languages (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    code VARCHAR(5) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);


CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    profile_image_url VARCHAR(500) NULL,
    fk_country INT NOT NULL DEFAULT 1,
    fk_language INT NOT NULL DEFAULT 1,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_countryC FOREIGN KEY (fk_country) REFERENCES countries(id),
    CONSTRAINT fk_languageC FOREIGN KEY (fk_language) REFERENCES languages(id)
);

CREATE TABLE user_roles (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_auth_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_auth_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);


CREATE TABLE privileges (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE roles_privileges (
    role_id INT NOT NULL,
    privilege_id INT NOT NULL,
    PRIMARY KEY (role_id, privilege_id),
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_privilege FOREIGN KEY (privilege_id) REFERENCES privileges(id) ON DELETE CASCADE
);

CREATE TABLE global_settings(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    value VARCHAR(255) NOT NULL
);


INSERT INTO roles (name, description) VALUES ('ROLE_ADMIN', 'Administrateur système');
INSERT INTO roles (name, description) VALUES ('ROLE_USER', 'Utilisateur standard');

INSERT INTO countries (code, name, phone_code) VALUES
('BE', 'Belgique', '+32'),
('FR', 'France', '+33'),
('DE', 'Germany', '+49'),
('NL', 'Netherlands', '+31'),
('LU', 'Luxembourg', '+352'),
('AF', 'Afghanistan', NULL),
('AX', 'Aland Islands', NULL),
('AL', 'Albania', NULL),
('DZ', 'Algeria', NULL),
('AS', 'American Samoa', NULL),
('AD', 'Andorra', NULL),
('AO', 'Angola', NULL),
('AI', 'Anguilla', NULL),
('AQ', 'Antarctica', NULL),
('AG', 'Antigua and Barbuda', NULL),
('AR', 'Argentina', NULL),
('AM', 'Armenia', NULL),
('AW', 'Aruba', NULL),
('AU', 'Australia', NULL),
('AT', 'Austria', NULL),
('AZ', 'Azerbaijan', NULL),
('BS', 'Bahamas', NULL),
('BH', 'Bahrain', NULL),
('BD', 'Bangladesh', NULL),
('BB', 'Barbados', NULL),
('BY', 'Belarus', NULL),
('BZ', 'Belize', NULL),
('BJ', 'Benin', NULL),
('BM', 'Bermuda', NULL),
('BT', 'Bhutan', NULL),
('BO', 'Bolivia', NULL),
('BQ', 'Bonaire, Sint Eustatius and Saba', NULL),
('BA', 'Bosnia and Herzegovina', NULL),
('BW', 'Botswana', NULL),
('BV', 'Bouvet Island', NULL),
('BR', 'Brazil', NULL),
('IO', 'British Indian Ocean Territory', NULL),
('BN', 'Brunei Darussalam', NULL),
('BG', 'Bulgaria', NULL),
('BF', 'Burkina Faso', NULL),
('BI', 'Burundi', NULL),
('CV', 'Cabo Verde', NULL),
('KH', 'Cambodia', NULL),
('CM', 'Cameroon', NULL),
('CA', 'Canada', NULL),
('KY', 'Cayman Islands', NULL),
('CF', 'Central African Republic', NULL),
('TD', 'Chad', NULL),
('CL', 'Chile', NULL),
('CN', 'China', NULL),
('CX', 'Christmas Island', NULL),
('CC', 'Cocos Islands', NULL),
('CO', 'Colombia', NULL),
('KM', 'Comoros', NULL),
('CG', 'Congo', NULL),
('CD', 'Congo, Democratic Republic of the', NULL),
('CK', 'Cook Islands', NULL),
('CR', 'Costa Rica', NULL),
('CI', 'Cote d Ivoire', NULL),
('HR', 'Croatia', NULL),
('CU', 'Cuba', NULL),
('CW', 'Curacao', NULL),
('CY', 'Cyprus', NULL),
('CZ', 'Czechia', NULL),
('DK', 'Denmark', NULL),
('DJ', 'Djibouti', NULL),
('DM', 'Dominica', NULL),
('DO', 'Dominican Republic', NULL),
('EC', 'Ecuador', NULL),
('EG', 'Egypt', NULL),
('SV', 'El Salvador', NULL),
('GQ', 'Equatorial Guinea', NULL),
('ER', 'Eritrea', NULL),
('EE', 'Estonia', NULL),
('SZ', 'Eswatini', NULL),
('ET', 'Ethiopia', NULL),
('FK', 'Falkland Islands', NULL),
('FO', 'Faroe Islands', NULL),
('FJ', 'Fiji', NULL),
('FI', 'Finland', NULL),
('GF', 'French Guiana', NULL),
('PF', 'French Polynesia', NULL),
('TF', 'French Southern Territories', NULL),
('GA', 'Gabon', NULL),
('GM', 'Gambia', NULL),
('GE', 'Georgia', NULL),
('GH', 'Ghana', NULL),
('GI', 'Gibraltar', NULL),
('GR', 'Greece', NULL),
('GL', 'Greenland', NULL),
('GD', 'Grenada', NULL),
('GP', 'Guadeloupe', NULL),
('GU', 'Guam', NULL),
('GT', 'Guatemala', NULL),
('GG', 'Guernsey', NULL),
('GN', 'Guinea', NULL),
('GW', 'Guinea-Bissau', NULL),
('GY', 'Guyana', NULL),
('HT', 'Haiti', NULL),
('HM', 'Heard Island and McDonald Islands', NULL),
('VA', 'Holy See', NULL),
('HN', 'Honduras', NULL),
('HK', 'Hong Kong', NULL),
('HU', 'Hungary', NULL),
('IS', 'Iceland', NULL),
('IN', 'India', NULL),
('ID', 'Indonesia', NULL),
('IR', 'Iran', NULL),
('IQ', 'Iraq', NULL),
('IE', 'Ireland', NULL),
('IM', 'Isle of Man', NULL),
('IL', 'Israel', NULL),
('IT', 'Italy', NULL),
('JM', 'Jamaica', NULL),
('JP', 'Japan', NULL),
('JE', 'Jersey', NULL),
('JO', 'Jordan', NULL),
('KZ', 'Kazakhstan', NULL),
('KE', 'Kenya', NULL),
('KI', 'Kiribati', NULL),
('KP', 'Korea, Democratic Peoples Republic of', NULL),
('KR', 'Korea, Republic of', NULL),
('KW', 'Kuwait', NULL),
('KG', 'Kyrgyzstan', NULL),
('LA', 'Lao Peoples Democratic Republic', NULL),
('LV', 'Latvia', NULL),
('LB', 'Lebanon', NULL),
('LS', 'Lesotho', NULL),
('LR', 'Liberia', NULL),
('LY', 'Libya', NULL),
('LI', 'Liechtenstein', NULL),
('LT', 'Lithuania', NULL),
('MO', 'Macao', NULL),
('MG', 'Madagascar', NULL),
('MW', 'Malawi', NULL),
('MY', 'Malaysia', NULL),
('MV', 'Maldives', NULL),
('ML', 'Mali', NULL),
('MT', 'Malta', NULL),
('MH', 'Marshall Islands', NULL),
('MQ', 'Martinique', NULL),
('MR', 'Mauritania', NULL),
('MU', 'Mauritius', NULL),
('YT', 'Mayotte', NULL),
('MX', 'Mexico', NULL),
('FM', 'Micronesia', NULL),
('MD', 'Moldova', NULL),
('MC', 'Monaco', NULL),
('MN', 'Mongolia', NULL),
('ME', 'Montenegro', NULL),
('MS', 'Montserrat', NULL),
('MA', 'Morocco', NULL),
('MZ', 'Mozambique', NULL),
('MM', 'Myanmar', NULL),
('NA', 'Namibia', NULL),
('NR', 'Nauru', NULL),
('NP', 'Nepal', NULL),
('NC', 'New Caledonia', NULL),
('NZ', 'New Zealand', NULL),
('NI', 'Nicaragua', NULL),
('NE', 'Niger', NULL),
('NG', 'Nigeria', NULL),
('NU', 'Niue', NULL),
('NF', 'Norfolk Island', NULL),
('MK', 'North Macedonia', NULL),
('MP', 'Northern Mariana Islands', NULL),
('NO', 'Norway', NULL),
('OM', 'Oman', NULL),
('PK', 'Pakistan', NULL),
('PW', 'Palau', NULL),
('PS', 'Palestine, State of', NULL),
('PA', 'Panama', NULL),
('PG', 'Papua New Guinea', NULL),
('PY', 'Paraguay', NULL),
('PE', 'Peru', NULL),
('PH', 'Philippines', NULL),
('PN', 'Pitcairn', NULL),
('PL', 'Poland', NULL),
('PT', 'Portugal', NULL),
('PR', 'Puerto Rico', NULL),
('QA', 'Qatar', NULL),
('RE', 'Reunion', NULL),
('RO', 'Romania', NULL),
('RU', 'Russian Federation', NULL),
('RW', 'Rwanda', NULL),
('BL', 'Saint Barthelemy', NULL),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', NULL),
('KN', 'Saint Kitts and Nevis', NULL),
('LC', 'Saint Lucia', NULL),
('MF', 'Saint Martin (French part)', NULL),
('PM', 'Saint Pierre and Miquelon', NULL),
('VC', 'Saint Vincent and the Grenadines', NULL),
('WS', 'Samoa', NULL),
('SM', 'San Marino', NULL),
('ST', 'Sao Tome and Principe', NULL),
('SA', 'Saudi Arabia', NULL),
('SN', 'Senegal', NULL),
('RS', 'Serbia', NULL),
('SC', 'Seychelles', NULL),
('SL', 'Sierra Leone', NULL),
('SG', 'Singapore', NULL),
('SX', 'Sint Maarten (Dutch part)', NULL),
('SK', 'Slovakia', NULL),
('SI', 'Slovenia', NULL),
('SB', 'Solomon Islands', NULL),
('SO', 'Somalia', NULL),
('ZA', 'South Africa', NULL),
('GS', 'South Georgia and the South Sandwich Islands', NULL),
('SS', 'South Sudan', NULL),
('ES', 'Spain', NULL),
('LK', 'Sri Lanka', NULL),
('SD', 'Sudan', NULL),
('SR', 'Suriname', NULL),
('SJ', 'Svalbard and Jan Mayen', NULL),
('SE', 'Sweden', NULL),
('CH', 'Switzerland', NULL),
('SY', 'Syrian Arab Republic', NULL),
('TW', 'Taiwan', NULL),
('TJ', 'Tajikistan', NULL),
('TZ', 'Tanzania', NULL),
('TH', 'Thailand', NULL),
('TL', 'Timor-Leste', NULL),
('TG', 'Togo', NULL),
('TK', 'Tokelau', NULL),
('TO', 'Tonga', NULL),
('TT', 'Trinidad and Tobago', NULL),
('TN', 'Tunisia', NULL),
('TR', 'Turkey', NULL),
('TM', 'Turkmenistan', NULL),
('TC', 'Turks and Caicos Islands', NULL),
('TV', 'Tuvalu', NULL),
('UG', 'Uganda', NULL),
('UA', 'Ukraine', NULL),
('AE', 'United Arab Emirates', NULL),
('GB', 'United Kingdom', NULL),
('UM', 'United States Minor Outlying Islands', NULL),
('US', 'United States', NULL),
('UY', 'Uruguay', NULL),
('UZ', 'Uzbekistan', NULL),
('VU', 'Vanuatu', NULL),
('VE', 'Venezuela', NULL),
('VN', 'Viet Nam', NULL),
('VG', 'Virgin Islands, British', NULL),
('VI', 'Virgin Islands, U.S.', NULL),
('WF', 'Wallis and Futuna', NULL),
('EH', 'Western Sahara', NULL),
('YE', 'Yemen', NULL),
('ZM', 'Zambia', NULL),
('ZW', 'Zimbabwe', NULL);

INSERT INTO languages(code, name) VALUES ('FR', 'Français');
INSERT INTO languages(code, name) VALUES ('EN', 'English');
INSERT INTO languages(code, name) VALUES ('NL', 'Nederlands');
INSERT INTO languages(code, name) VALUES ('DE', 'Deutsch');

INSERT INTO global_settings (name, value) VALUES ('registration_enabled', 'true');
